### ISSUE TITLE
Added contact not showing up without manually refreshing the contact manager on Android

### ISSUE THREAD

**Issue by Proberts** [rt2zz/react-native-contacts#122]
_Sorry if this is the wrong place for this. I encountered this working on my fork that I hope to merge back in_.

It seems that on some Android phones, possibly those not using the stock contacts app, newly added contacts do not show up in the contact manager right away. This appears to be a known issue, and related to the new contact not being assigned to a default group when added. Only after the database is rescanned and the new contact is discovered to not have a group is the default group assigned.

I don't see this on my Galaxy Note 3 or S7, but I do see it on my LG K7, and it apparently happens on some HTC and Motorola handsets (based on SO posts).

Has anyone else has experienced this, and if so how did you work around it?

**Comment by morenoh149** [comment]
I think there are some delay due to writing to the filesystem. I would simply map the getAll() call to a pull to refresh interaction and the new contacts would be picked up. I would doublecheck to see if the Android api can return a signal when the contact is made available, otherwise I don't see any way around polling the contacts db every 1000ms.

**Comment by iagorm** [comment]
This is still happens, maybe add an event to RN and in the javascript method would be something like:

```
getAll({onRefresh: this.updateList})
.then(this.updateList)
```
