### ISSUE TITLE
Getting Error When Fetching Contacts. 

### ISSUE THREAD

**Issue by cacheflow** [rt2zz/react-native-contacts#15]
I'm slightly new to React native and Objective C, but I recently tried to use this package in an app I'm working on and keep getting this error when calling the getAll function: 

Exception thrown while invoking getAll on target RCTContacts with params (
    7
): *** setObjectForKey: object cannot be nil (key: thumbnailPath)

Initially I assumed it was related to not using the new Contacts API, so I tried rewriting the getAll function using it, but ran into some problems. Any idea on how I can fix the above? This is the code I'm using in my index.ios.js:

Contacts.getAll(function(error, contacts) {
      if(error && error.type === 'permissionDenied'){
        console.log(err);
      } else {
        console.log(contacts);
      }

**Comment by rt2zz** [comment]
Not sure why you are getting that error. My recommendation would be to do one of the following
1) try out https://github.com/JeanLebrument/react-native-contacts/tree/feature/moreInfosFromUser
2) try changing all return statements in https://github.com/rt2zz/react-native-contacts/blob/master/ios/RCTContacts/RCTContacts.m#L167 to return @"" instead of nil
