### ISSUE TITLE
Can the contact creation date be retrieved?

### ISSUE THREAD

**Issue by javidjamae** [rt2zz/react-native-contacts#200]
I just installed the library and gave it a shot on iOS, but I see that the data that comes back does not include any date information for the contact record. Specifically, I need the creation date of the contact record. Is it possible to obtain the creation date?

**Comment by soutot** [comment]
As far as I know there's no such a field to store this information.
For new users a workaround would be geting the date and store it in 'Note' property
https://github.com/rt2zz/react-native-contacts/issues/189

It would be better to store it in a database and thus get the date from the server instead of client, so you wouldn't face any issue regarding timezone

**Comment by sbobryk** [comment]
Same case.
If I'm not gonna use Note property? Any suggestions?

**Comment by morenoh149** [comment]
the underlying apis do not allow this

**Comment by codeundercoverdev** [comment]
Hi, I am trying to do this now.  I know it is possible because there is an app called "Recent contacts" that does just this.  Has anyone had any luck in figuring this out?
