### ISSUE TITLE
birthday is undefined in iOS

### ISSUE THREAD

**Issue by taiale** [rt2zz/react-native-contacts#252]
I setup Anna contact in iPhone X simulator that has birthday field but when I call functions `getAll` it not return the birthday field. Please see the picture as the result

<img width="545" alt="screen shot 2018-02-12 at 11 26 56 am" src="https://user-images.githubusercontent.com/6778789/36083698-0642d672-0fe8-11e8-8222-ede6c58eb51a.png">
<img width="251" alt="screen shot 2018-02-12 at 11 27 23 am" src="https://user-images.githubusercontent.com/6778789/36083699-0ad796fa-0fe8-11e8-9319-8c9e9ac3874f.png">

Thanks,

**Comment by UniverseHan** [comment]
same issue

**Comment by UniverseHan** [comment]
fixed this issue and merged into master. But not applied npm module 2.1.1.
You can use this from npm install from github master branch directly by this commend

`npm install rt2zz/react-native-contacts#master`

**Comment by morenoh149** [comment]
@UniverseHan I don't believe that's true. If you've solved the issue please submit a PR.

**Comment by UniverseHan** [comment]
someone solved this already. See #244. But It seems not release as npm module yet. I installed react-native-contracts by master branch.

I got

![image](https://user-images.githubusercontent.com/11917873/36927441-f9a9f444-1ec0-11e8-9081-00689cd6bdec.png)

![image](https://user-images.githubusercontent.com/11917873/36927454-0c29fd1c-1ec1-11e8-9e39-d49a6b50ada0.png)

**Comment by morenoh149** [comment]
@UniverseHan this is very odd. I investigated and you're right the birthday code wasn't published on npm. I just published 2.1.2 and verified it has the birthday code. Please confirm it works for you so we can close this issue.

**Comment by UniverseHan** [comment]
I have tried again by react-native-contacts:2.1.2. It works well. 

I changed its version to 2.1.2 then reinstall through this
```bash
npm i
react-native unlink react-native-contacts
react-native link react-native-contacts
react-native run-ios
```
This is my bash history.

![image](https://user-images.githubusercontent.com/11917873/36943929-8448d9e8-1fd5-11e8-828d-5b961aee690f.png)

![image](https://user-images.githubusercontent.com/11917873/36943919-50a7996c-1fd5-11e8-8b4b-42d76a333327.png)

You can close this issue.

One more thing. As you see in screenshot Birthday's month start from 0 instead of 1. Should it be changed or not? Do I have to open another issue?

![image](https://user-images.githubusercontent.com/11917873/36944008-aaad8e2a-1fd6-11e8-8063-09df34ab140c.png)

I don't know it is right behavior because normal date month object start from 0.

**Comment by morenoh149** [comment]
I think that is normal behavior. The main thing is the behavior should be the same for android and ios, if they are not please open an issue.

**Comment by shalini-github** [comment]
I am trying to import the contacts with birthday field. After import, it shows wrong birthday, due to month starts from 0. how to resolve this in iOS? It works fine in android app.

**Comment by morenoh149** [comment]
@shalini-github open a fresh issue to track the discrepancy. And submit a PR for the ios birthday parsing.
