### ISSUE TITLE
Last time contacted

### ISSUE THREAD

**Issue by morenoh149** [rt2zz/react-native-contacts#29]
Does ios have the ability to query the last time contacted? http://developer.android.com/reference/android/provider/ContactsContract.ContactOptionsColumns.html#LAST_TIME_CONTACTED

for my app idea this information would be very nice to have.

**Comment by rt2zz** [comment]
I am about 80% sure iOS does not have this options although things may be different in the new Contact Framework (https://developer.apple.com/library/watchos/documentation/Contacts/Reference/Contacts_Framework/index.html)

**Comment by pickhardt** [comment]
I'm pretty sure it's not possible on iOS, but on Android I'm pretty sure there are permissions to read their texts and phone call log. That seems out of scope for this repo however, since it's really just a contacts and address book repo.

**Comment by morenoh149** [comment]
I think information related to contacts (such as the last time contacted) is within scope for this module but impossible to support on iOS. Perhaps another native module is warranted?

**Comment by pickhardt** [comment]
I mean, maybe it's in scope, and I could see an argument for it. It's up to @rt2zz  From my point of view, I wouldn't want to add those permissions to use this repo, since they appear pretty invasive, but if the repo had the functionality I wouldn't be opposed either as long as it was clear I only have to add the permissions to access text messages or phone logs.
