### ISSUE TITLE
familyName and givenName get added together

### ISSUE THREAD

**Issue by npomfret** [rt2zz/react-native-contacts#39]
When adding a new contact on Android, the familyName field and givenName field get concatenated.  The result is that familyName is empty, and givenName contains the concatenation.

**Comment by morenoh149** [comment]
This is intentional and noted https://github.com/rt2zz/react-native-contacts#example-contact-record thought it could probably use fleshing out in the readme. The limitation stems from our use of the Contactables table, and there Android concats the familyName and GivenName into a [DisplayName](https://developer.android.com/reference/android/provider/ContactsContract.ContactsColumns.html#DISPLAY_NAME)

The module then returns the display name in the firstname field (to maintain backwards compatability with ios). If you are willing to dive into Android development I can suggest ideas for how to change this.

**Comment by npomfret** [comment]
Ah, thanks - I missed that.
