### ISSUE TITLE
Change versioning to semver

### ISSUE THREAD

**Issue by patrisk** [rt2zz/react-native-contacts#70]
Could you consider changing your versioning system to semver?

The latest update from 0.2.7 to 0.2.8 includes breaking changes and it broke an app I'm developing.

**Comment by morenoh149** [comment]
@patrisk the real problem is understanding what is and is not a breaking change. I've been reserving minor bumps to when the api has obviously changed. E.g., `foo(a,b,c)` becomes `foo(a,b)`. Short of extensive testing or guessing I don't see how to determine what is and is not a breaking change. If you'd like to volunteer upcoming versions I'd really appreciate it :)
